services:
  dev:
    container_name: obs-rec
    image: obs-rec
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - obs-rec:/workspace
      - uv_cache:/root/.cache/uv
      - pip_cache:/root/.cache/pip
      - pre-commit_cache:/root/.cache/pre-commit
    environment:
      - PYRIGHT_PYTHON_FORCE_VERSION=latest
    tty: true
    working_dir: /workspace
    command: /bin/bash
    stop_grace_period: 0s

volumes:
  obs-rec:
    name: obs-rec
  uv_cache:
  pip_cache:
  pre-commit_cache:
